
server:
  port: 8080

spring:
  application:
    name: xiaomi-feign
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
    client-name:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    "UserService#saveOrder(Integer, Integer)":
      fallback:
        enabled: true